Use the user image for BBB avatar #2 (Limit image size)
bigbluebutton/greenlight pull request #2860
Opened 2021-07-30 12:10 UTC by hiroshisuga

## Description
This is basically a modified version of #2308, passing the user image of GL to BBB for displaying it as the avatar. However this version limits the size of the avatar so that BBB can avoid being crashed by somebody sending a huge image as the avatar.

The maximum size can be set by the parameter AVATAR_SIZE_LIMIT in .env file. 

This PR is sent as a workaround until GL implements more sophisticated system for uploading images.

## Testing Steps
1. Start a meeting with the user image set on GL.
2. See the avatar on BBB.
3. Another user joins the meeting with the user image set on GL
4. See his avatar as well.

## Screenshots (if appropriate):

2021-08-02 05:53 UTC, hiroshisuga commented
I have fixed an error from Rubocop. I forgot to check if the URL is valid.

2021-08-02 13:04 UTC, ffdixon commented
Thanks @hiroshisuga for this.

2021-09-12 16:45 UTC, farhatahmad requested changes

2021-09-12 16:45 UTC, farhatahmad commented on sample.env
> +AVATAR_SIZE_LIMIT=50000
Lets up this limit to 100000 bytes instead

2021-09-12 16:45 UTC, farhatahmad commented on app/controllers/concerns/bbb_server.rb
> +    join_opts[:avatarURL] = options[:avatarURL] if options[:avatarURL].present? && options[:avatarURL_size] < ENV['AVATAR_SIZE_LIMIT'].to_i
Can we move the logic for validating the image size into the controller instead? 

```
join_opts[:avatarURL] = options[:avatarURL] if options[:avatarURL].present?
```

2021-09-12 16:45 UTC, farhatahmad commented on app/controllers/concerns/joiner.rb
> +  include ApplicationHelper
Helpers should only be used in views, so this can be removed (see below)

2021-09-12 16:45 UTC, farhatahmad commented on app/controllers/rooms_controller.rb
> +  include ApplicationHelper
This can be removed (see below)

2021-09-12 16:45 UTC, farhatahmad commented on app/helpers/application_helper.rb
> +  def url_size(url)
Can we move this to a private method in the `rooms_controller` instead?

2021-09-12 16:45 UTC, farhatahmad commented on app/controllers/rooms_controller.rb
> +    opts[:avatarURL] = current_user.image
I would move the size logic into here 
```
opts[:avatarURL] = current_user.image if current_user.image.present? && valid_avatar?(current_user.image)
```
(see below for `valid_avatar?`)

2021-09-12 16:45 UTC, farhatahmad commented on app/helpers/application_helper.rb
> +  def url_size(url)
I would also replace this with something less general.

```
  def valid_avatar?(url)
    return false if URI.regexp.match(url).nil?
    uri = URI(url)
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true if uri.scheme == 'https'
    response = http.request_head(uri)
    return response['content-length'].to_i < Rails.configuration.max_avatar_size
  end
```

2021-09-12 16:45 UTC, farhatahmad commented on app/helpers/application_helper.rb
> +  def url_size(url)
Also, avoid accessing the `ENV` variable directly and set it in `config/application.rb` instead

2021-09-12 16:49 UTC, farhatahmad commented on app/controllers/concerns/joiner.rb
> +        opts[:avatarURL] = current_user.image
I would move the size logic into here

```
opts[:avatarURL] = current_user.image if current_user.image.present? && valid_avatar?(current_user.image)
```

(see below for valid_avatar?)

2021-09-13 06:27 UTC, hiroshisuga commented
@farhatahmad , thanks for the great suggestion. I modified the PR accordingly. In my place it is working as expected. Would be great if you can test it as well.

2021-09-13 08:52 UTC, hiroshisuga commented on sample.env
> +AVATAR_SIZE_LIMIT=100000
@farhatahmad , would you prefer MAX_AVATAR_SIZE here?

2021-09-14 00:48 UTC, hiroshisuga commented
I modified the code a bit. It's working as expected.

A notification to users might be necessary in the user profile setting. Or we may have to limit the size of the profile picture as well.

2021-09-18 22:56 UTC, farhatahmad commented
This is fantastic. Thank you @hiroshisuga !

2021-09-18 22:56 UTC, farhatahmad approved these changes

2021-09-18 22:56 UTC, merged