Rooms front end test
bigbluebutton/greenlight pull request #3373
Opened 2022-04-06 20:23 UTC by hadicheaito1

## Description

- Front end test for Rooms page, using Jest
## Testing Steps

## Screenshots (if appropriate):

2022-04-08 21:13 UTC, scouillard commented
It seems like every aria-label, aria-control and id are dynamically rendered on every test run, which make the snapshot test fail every time.

I think one way to solve the issue would be to expect any() for the listed properties above.
https://jestjs.io/docs/snapshot-testing#property-matchers

Or to hard code the properties.
https://stackoverflow.com/questions/53354341/react-jest-snapshot-testing-with-dynamic-id

2022-04-08 21:27 UTC, scouillard commented
Running `jest -u` will re-generate snapshot artifacts for all failing snapshot tests, and should be used only when there is change in the DOM/layout.

2022-04-11 10:55 UTC, KH-Amir-TN requested changes

2022-04-11 10:55 UTC, KH-Amir-TN commented on app/javascript/__tests__/rooms/Rooms.test.jsx
> +    const json = useRooms();
We are testing a mock here. 
To test queries we should mock the API calls but use the queries original implementation.

2022-04-11 10:55 UTC, KH-Amir-TN commented on app/javascript/__tests__/rooms/Rooms.test.jsx
> +const rooms = {
I think this is not useful since it's in place only to test a mock.

2022-04-11 10:59 UTC, KH-Amir-TN commented
> It seems like every aria-label, aria-control and id are dynamically rendered on every test run, which make the snapshot test fail every time.
> 
> I think one way to solve the issue would be to expect any() for the listed properties above via Property Matchers. https://jestjs.io/docs/snapshot-testing#property-matchers
> 
> Or to hard code the properties directly in the prop. https://stackoverflow.com/questions/53354341/react-jest-snapshot-testing-with-dynamic-id
> 
> I've been trying both solutions so far without success.

You had this problem when pulling this PR or on one that you're working on?

2022-04-11 13:46 UTC, scouillard commented
> > It seems like every aria-label, aria-control and id are dynamically rendered on every test run, which make the snapshot test fail every time.
> > I think one way to solve the issue would be to expect any() for the listed properties above via Property Matchers. https://jestjs.io/docs/snapshot-testing#property-matchers
> > Or to hard code the properties directly in the prop. https://stackoverflow.com/questions/53354341/react-jest-snapshot-testing-with-dynamic-id
> > I've been trying both solutions so far without success.
> 
> You had this problem when pulling this PR or on one that you're working on?

On this PR.

2022-04-21 16:12 UTC, closed without merging