Solved Critical Issue Allowing Users to Change their Role
bigbluebutton/greenlight pull request #4312
Opened 2022-12-21 20:17 UTC by alihadi-mazeh

## Description

## Testing Steps

## Screenshots (if appropriate):

2022-12-21 20:33 UTC, hadicheaito1 requested changes

2022-12-21 20:33 UTC, hadicheaito1 commented on spec/controllers/users_controller_spec.rb
> +    it 'allows an admin to edit themself' do
Instead I'd say, "allows a user with ManageUsers permission to edit their own role"

2022-12-21 20:33 UTC, hadicheaito1 commented on spec/controllers/users_controller_spec.rb
> +    it 'allows an admin to edit someone else' do
I'd say, "allows a user with ManageUsers permission to edit  another users role"

2022-12-21 20:33 UTC, hadicheaito1 commented on app/controllers/api/v1/users_controller.rb
> +
remove this extra empty line

2022-12-22 19:01 UTC, hadicheaito1 commented
@alihadi-mazeh You have a rubocop complaint. You also accidentally put the same description twice for two different tests

2023-01-04 19:27 UTC, farhatahmad approved these changes

2023-01-04 19:27 UTC, merged